<a href="https://colab.research.google.com/github/mushfiqur11/NumericalAnalysisMethods/blob/master/160041011_NumericalAnalysisLab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numerical Analysis Lab

## Md. Mushfiqur Rahman
### 160041011

##Lab - 3

In [0]:
import numpy as np
import matplotlib.pyplot as plt

### Task 01

#### Implementation of Newton Divided Difference Method

The following function is an implementation of the Newton Divided Difference Method. The function takes in 3 inputs. Arrays x and y of same size and an integer n. From the three values, $b_0 , b_1, b_2 ... b_n$ are calculated.
First a 2D array was taken. Here, each column represent the a series of f. The first column of the array is the y itself. In the each consecutive column, $f$ was calculated using the formula of Newton Divided Difference. The topmest element of each column, that is, the entire first row is basically the array $b_0 , b_1, b_2 ... b_n$.

In [0]:
def NewtonDividedDifference(x, y, n):
    if (n> np.shape(y)[0]):
      n=np.shape(y)[0]
    pyramid = np.zeros([np.shape(y)[0], np.shape(y)[0]])
    pyramid[::,0] = y
    s=np.shape(y)[0]
    for j in range(1,n):
        for i in range(s-j):
            pyramid[i][j] = (pyramid[i+1][j-1] - pyramid[i][j-1]) / (x[i+j] - x[i])
    return [pyramid[0], n]

In [0]:
NewtonDividedDifference([10,15,20,22.5,30],[227.04,362.78,517.35,602.97,901.67],6)

[array([2.27040000e+02, 2.71480000e+01, 3.76600000e-01, 5.43466667e-03,
        1.06044444e-04]), 5]

The following function uses the Newton Divided Difference function created above to calculate the y of a given x. The function takes in 4 inputs. One of them is the value of x. The other three are respectively array X, array Y and integer n. X, Y and n are used to find the $b0,b1,b2...bn$ and then y is calculated from it using the formula: $$ y= b_0+b_1(x-x_0)+b_2(x-x_0)(x-x_1) + ...$$

In [0]:
def NewtonDividedDifferenceInterpolation(val, X, Y, N):
  [pyramid,n] = NewtonDividedDifference(X,Y,N)
  calculatedValue = 0
  temp = np.ones(np.shape(pyramid)[0])
  for i in range(0,n-1):
    for j in range(0,i):
      temp[j] = val-X[j]
      #print(val - X[j])
    print(temp)
    newVal = pyramid[i]
    for j in range(0,i):
      newVal = newVal * temp[j]
    calculatedValue = calculatedValue + newVal
    print(calculatedValue)
  return calculatedValue

In [0]:
NewtonDividedDifferenceInterpolation(16,[10,15,20,22.5,30],[227.04,362.78,517.35,602.97,901.67],4)

[1. 1. 1. 1. 1.]
227.04
[6. 1. 1. 1. 1.]
389.928
[6. 1. 1. 1. 1.]
392.18760000000003


392.18760000000003